export const STATUS__NORMAL = 'NORMAL';
export const PLAYER_ACTIONS = {
  SET_STATUS: 'PLAYER_SET_STATUS',
  NEW_PLAYER_EDIT: 'NEW_PLAYER_EDIT',
  CREATE_PLAYER: 'CREATE_PLAYER',
  NEW_PLAYER_CHANGE: 'NEW_PLAYER_CHANGE',
  NEW_PLAYER_SAVE: 'NEW_PLAYER_SAVE'
};
