export const PLAYER_STATUS = {
	NORMAL: 'NORMAL'
};

export const PLAYER_ACTIONS = {
	SET_STATUS: 'PLAYER_SET_STATUS',
	NEW_PLAYER_EDIT: 'NEW_PLAYER_EDIT',
	CREATE_PLAYER: 'CREATE_PLAYER',
	NEW_PLAYER_CHANGE: 'NEW_PLAYER_CHANGE',
	NEW_PLAYER_SAVE: 'NEW_PLAYER_SAVE',
	UPDATE_DRAGGING: 'UPDATE_DRAGGING',
	EDIT_EXISTING_PLAYER: 'EDIT_EXISTING_PLAYER',
	UPDATE_EXISTING_PLAYER: 'UPDATE_EXISTING_PLAYER'
};

export const INITIATIVE_ACTIONS = {
	INSERT_BEFORE: 'INSERT_BEFORE',
	INSERT_AT_END: 'INSERT_AT_END',
	REMOVE_PLAYER: 'REMOVE_PLAYER'
};

export const UI_ACTIONS = {
	PLAYER_DRAG_UPDATE: 'PLAYER_DRAG_UPDATE'
};

export const DRAG_TYPES = {
	PLAYER: 'PLAYER'
};

export const MODIFIER_CLASSES = {
	IS_DRAGGABLE: 'is-draggable'
};
